name: Package / Publish

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  id-token: write
  attestations: write
  artifact-metadata: write

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install system deps
        run: sudo apt-get update && sudo apt-get install -y xvfb

      - name: Install dependencies
        run: npm ci

      - name: Verify tag matches package version
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          TAG="${GITHUB_REF_NAME#v}"
          PKG_VERSION="$(node -p \"require('./package.json').version\")"
          if [ "${TAG}" != "${PKG_VERSION}" ]; then
            echo "Tag v${TAG} does not match package.json version ${PKG_VERSION}"
            exit 1
          fi

      - name: Run tests (e2e)
        run: npm run test:ci

      - name: Package (.vsix)
        run: npm run vsce:package

      - name: Generate checksums
        run: sha256sum *.vsix > SHA256SUMS

      - name: Attest build provenance (GitHub)
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: "*.vsix"

      - name: Upload .vsix artifact
        uses: actions/upload-artifact@v4
        with:
          name: vsix
          path: |
            *.vsix
            SHA256SUMS

      - name: Publish (if VSCE_PAT is set)
        if: ${{ secrets.VSCE_PAT != '' }}
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: |
          VSIX_PATH="$(ls -1 *.vsix | head -n 1)"
          npm run vsce:publish -- --packagePath "${VSIX_PATH}" -p "${VSCE_PAT}"

      - name: Create GitHub Release (tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            *.vsix
            SHA256SUMS
          generate_release_notes: true
